services:
  giapha_web:
    build:
      context: .
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY}
    # ports:
    #  - "3000:3000"
    restart: always
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=${NEXT_PUBLIC_SUPABASE_URL}
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.giapha_web.rule=Host(`giapha.appweb.io.vn`)"
      - "traefik.http.routers.giapha_web.entrypoints=web"
networks:
  web:
    external: true